### ISSUE TITLE
Magicka Mastery by MageKing17 doens't work

### ISSUE THREAD

**Issue by RandomPal** [MWSE/MWSE#116] opened 2018-09-16 14:27 UTC
Breif discussion here: https://www.reddit.com/r/Morrowind/comments/9g99sr/magicka_mastery_broken_with_the_lasted_mwse/

**Comment by NullCascade** [comment] 2018-09-16 14:45
> Weird, are we talking about the same mod? There might be some confusion since more than one mod has a similar name. This one is a 2017 mod, and it states in the description:
>
> ''This mod requires MWSE 0.9.5-alpha.20151016. Versions as early as 0.9.5-alpha.20150707 will possibly work, but there's no real reason not to use the latest.''
>
> I can't give super precise information about what build I was using, but I tried to always stay up to date. Than I took a break from MW for some months, and when I came back I discovered the new amazing version of MWSE and all the crazy mods that are coming out. I rolled a new character and I sadly discovered that Magicka Mastery was broken. This is the best I can do, I'm willing to do some testing if it can be of any help, I know how to use the CS and the various tools, but unfortunately I know nothing about scripting.
>
> And thank you for the new MWSE version :)

I'm not completely sure of it, I'm going off 2nd hand information. If you could test the different versions and let me know if it broke *after* v0.9.5-alpha.20171111, we can determine where and the priority of the break.

From what G7 said, the break was from 20171111's change to `xGetMagic`, which allows a reference. This happened [in the old branch](https://github.com/Merzasphor/MWSE/commit/5135491da0c3aba4aba2bda0932264fb76c511bf).

@Greatness7 : Do you think it'd be safe to change `xGetMagic` to default to the player if no other reference is provided would fix backwards compatibility while working with any new mods? On that line, do you know why Merzaphor made this change? Do any mods take advantage of `xGetMagic` with a specified reference?

**Comment by RandomPal** [comment] 2018-09-16 15:06
Ok, tested and double-checked. 
1. MWSE v0.9.5-alpha.20171006: works
2. MWSE v0.9.5-alpha.20171111: doesn't work
3. 2+: I'm using the more updated version (latest update this morning) and it doesn't work

**Comment by NullCascade** [comment] 2018-09-16 16:29
@RandomPal Thanks for testing. This confirms that G7 is right about the issue. We'll brainstorm on how to deal with it. Unfortunately mods are making use of the change, so we can't undo it.

**Comment by RandomPal** [comment] 2018-09-16 16:47
@NullCascade Glad I could help. I'll stay tuned!

**Comment by Greatness7** [comment] 2018-09-16 16:50
> 
> 
> Breif discussion here: https://www.reddit.com/r/Morrowind/comments/9g99sr/magicka_mastery_broken_with_the_lasted_mwse/

Here's a fixed version of the original ESP:
[MagickaMastery (halved progression).esp](https://www.dropbox.com/s/4qcclsjxg99rgr1/MagickaMastery%20%28halved%20progression%29.esp?dl=0)

Or alternatively, a lua port of the mod:
[masteringMagickaLua](https://www.dropbox.com/s/639okrw5v37bb3k/masteringMagicka.zip?dl=0)

The lua versions should be a bit more efficient and some benefits of not needing an ESP and working also working for NPCs rather than just the player. Just be sure not to use both versions together.

**Comment by RandomPal** [comment] 2018-09-16 17:34
@Greatness7 I did a quick testing and both versions work great. Having the lua version also working on NPCs is a very nice addition.
You should really get in touch with mageking17 and release the mod.
Thanks guys!

**Comment by NullCascade** [comment] 2018-09-17 08:50
Posted this on his Nexus page. I pinged MageKing17 on his Nexus page about the fixed ESP, and the cause for the issue.

For now, I'm flagging this as won't fix, and hope that MageKing17 updates his mod with G7's changes. If this continues to be an issue in the future we can reevaluate.

**Closed by NullCascade** 2018-09-17 08:50 UTC
Labels: bug, won't fix

**Comment by MageKing17** [comment] 2018-12-08 07:50
Hey guys; I was having some computer problems, so I only just saw the link to this issue. That Lua version is really cool; avoids a lot of hackish workarounds. @Greatness7, @NullCascade, may I use that as the basis for the next update? It's a really quite elegant upgrade, assuming it works as it seems to from reading the code.

**Comment by Greatness7** [comment] 2018-12-08 20:14
> Hey guys; I was having some computer problems, so I only just saw the link to this issue. That Lua version is really cool; avoids a lot of hackish workarounds. @Greatness7, @NullCascade, may I use that as the basis for the next update? It's a really quite elegant upgrade, assuming it works as it seems to from reading the code.

Sure, feel free to use it how ever you wish!

One thing to note: The majority of that lua code was spent updating the GUI. This is no longer needed as we have functions which handle that automatically when modifying a statistic (tes3.setStatistic).

Here's an updated version using said function: https://www.dropbox.com/s/ubq4p1xjrgj1seu/magickaMastery.zip?dl=0

**Comment by Pherim** [comment] 2020-01-17 17:42
Where do I put the lua version? I suppose into MWSE/mods? How do I know it's working?
