### ISSUE TITLE
registering weaponReadied and attack events bug

### ISSUE THREAD

**Issue by strelocc** [MWSE/MWSE#223] opened 2019-09-02 11:24 UTC
i registered a function on weaponReadied event, but now when i press the key to ready the weapon it keeps playing the animation, it's not an animation bug because the code registered to the event keeps being executed every time, it keeps doing it until i press the ready weapon key again

also when this happens it's impossible to attack

the code inside the function registered to weaponReadied is executed correctly and there are no error or messages in the log file

---------
now i registered a function to attack event, the code executes but as soon the attack animation ends the weapon is holstered and readied again

---------

Morrowind Script Extender v2.1.0 (built Aug 26 2019) hooked.
Found MGE XE. Version: 0.11.6.0

**Comment by OperatorJack** [comment] 2020-01-24 14:25
@strelocc Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can reproduce this issue. I am not able to reproduce this issue in my environment and will close it if additional information isn't provided.

**Closed** 2022-01-19 16:06 UTC
